= 📝 AULAJA



Nosso grupo é composto por mim, Vitor Eduardo Eleoterio, Paulo Henrique André e Hellen Gabriela Scarantti. Nosso objetivo é desenvolver um aplicativo web com seis telas, voltado para o ambiente escolar. O app será baseado no Google Classroom, porém com algumas modificações para torná-lo mais simples e intuitivo para os usuários.

Nosso protótipo é composto pelas seguintes telas:

Tela de Login: onde o usuário informa seu nome de usuário e senha para acessar o sistema.

Tela de Cadastro: onde o usuário pode criar uma nova conta, fornecendo nome de usuário, senha e confirmação da senha.

Tela Principal: apresenta um calendário e, abaixo dele, uma lista com algumas atividades. Na parte inferior da tela, há três botões: Atividades, Mural e Pessoas.

Tela de Atividades: exibe uma lista com atividades fictícias. No canto superior esquerdo há uma seta para retornar à tela principal.

Tela do Mural: apresenta o calendário completo, onde o usuário pode visualizar provas e atividades futuras. Essa tela utilizará uma API de calendário para integrar e exibir esses dados. Também possui um botão no canto superior esquerdo para retornar à tela principal.

Tela de Pessoas: mostra diversos cards com os perfis das pessoas cadastradas no aplicativo. Essa tela obterá os dados por meio de uma API que puxa as informações relevantes para a listagem.

